version: "3.7"
services:
  drintan:
    container_name: drintan
    image: nginx:latest
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - msa-networks
    ports:
      - 8107:80
    restart: always

networks:
  msa-networks:
    driver: bridge
    name: msa-networks
    external: true
